version: "3.7"

services:
    db:
        image: postgres
        restart: always
        container_name: finance.angelin.dev-db
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=finance
        ports:
            - 5432:5432
volumes:
    db:
